Minor fixes
Acors24/one-of-the-repos-ever pull request #153
Opened 2024-05-17 10:47 UTC by Acors24

2024-05-18 09:12 UTC, MateuszM02 requested changes
It fails on my machine:
![Desktop Screenshot 2024 05 18 - 11 10 09 77](https://github.com/Acors24/one-of-the-repos-ever/assets/96058912/e24fe5d6-c6c1-4bfc-ba35-bec4bfad19fc)

2024-05-18 15:44 UTC, Acors24 commented
> It fails on my machine: ![Desktop Screenshot 2024 05 18 - 11 10 09 77](https://private-user-images.githubusercontent.com/96058912/331782484-e24fe5d6-c6c1-4bfc-ba35-bec4bfad19fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDcyNzYsIm5iZiI6MTcxNjA0Njk3NiwicGF0aCI6Ii85NjA1ODkxMi8zMzE3ODI0ODQtZTI0ZmU1ZDYtYzZjMS00YmZjLWJhMzUtYmVjNGJmYWQxOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE1NDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODBiZWJjM2Y5ZmY3ZTk0ZDA3NmViYmI0YmJiN2QzZDYxNGRmMDU2ZmNmZjBmMTY3Y2RlZTViNWRlNTE1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jl2zCcCsU_vnM3XmjSPwOdPph5v8HctlIkcrGSBMaWI)

delete windows

2024-05-22 06:16 UTC, hrmnpfg approved these changes

2024-05-22 06:23 UTC, MateuszM02 approved these changes
Na maszynie Michała działa.

2024-05-22 06:23 UTC, merged